// CutiScreenStyles.js
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  scrollContent: { paddingLeft: 10, paddingRight: 10 },
  tabBar: { flexDirection: "row" },
  tabItem: {
    color: "#aaa",
    marginRight: 16,
    fontFamily: "Poppins_600SemiBold",
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  tabItemActive: {
    color: "#1E2D56",
    fontWeight: "bold",
    fontFamily: "Poppins_700Bold",
    borderBottomWidth: 2,
    borderBottomColor: "#1E2D56",
  },
  dateRangeBox: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dateRangeText: {
    color: "#1E2D56",
    fontWeight: "500",
    fontFamily: "Poppins_600SemiBold",
    backgroundColor: "#E7EFFD",
    padding: 10,
    borderRadius: 8,
  },
  iconsRight: { flexDirection: "row", alignItems: "center" },
  summaryBox: {
    backgroundColor: "#eef3ff",
    borderRadius: 16,
    marginTop: 10,
    marginBottom: 10,
  },
  summaryHeader: {
    flexDirection: "row",
    backgroundColor: "#223B82",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 6,
  },
  summaryTitle: {
    flex: 1,
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
    fontFamily: "Poppins_700Bold",
  },
  summaryRow: {
    flexDirection: "row",
    paddingVertical: 8,
  },
  summaryLabel: {
    flex: 1,
    textAlign: "left",
    color: "#000",
    paddingLeft: 15,
    fontFamily: "Poppins_500Medium",
  },
  summaryValue: {
    fontSize: 15,
    color: "#000",
  },
  valueCell: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  filterBar: { flexDirection: "row", marginBottom: 12 },
  filterItem: {
    marginRight: 12,
    color: "#999",
    fontFamily: "Poppins_600SemiBold",
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  filterItemActive: {
    backgroundColor: "#1E2D56",
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
    color: "#fff",
  },
  card: {
    backgroundColor: "#fff",
    elevation: 8,
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    shadowColor: "#888",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardTitle: {
    fontWeight: "bold",
    fontSize: 16,
    fontFamily: "Poppins_700Bold",
  },
  cardSub: {
    color: "#666",
    marginTop: 6,
    fontFamily: "Poppins_600SemiBold",
    marginBottom: 5,
  },
  cardRow: { flexDirection: "row", alignItems: "center", marginTop: 4 },
  cardDate: {
    marginLeft: 4,
    color: "#333",
    fontFamily: "Poppins_500Medium",
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  statusText: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Poppins_700Bold",
  },
  statusX: {
    color: "#fff",
    fontSize: 14,
    backgroundColor: "red",
    paddingHorizontal: 5,
    paddingVertical: 4,
    borderRadius: 20,
    fontWeight: "bold",
  },
  viewButton: { alignSelf: "flex-end" },
  viewText: { color: "#1E2D56", fontWeight: "bold" },
  fab: {
    position: "absolute",
    bottom: 40,
    right: 24,
    backgroundColor: "#1E2D56",
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
  },
  fabText: { color: "#fff", fontSize: 32, lineHeight: 32 },
  yearModal: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  yearModalContent: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    width: "80%",
  },
  yearModalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
});

export default styles;
